version: '3'

services:
  api:
    container_name: "permission-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: permission-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true