version: '3'

services:
  api:
    container_name: "permission-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: permission-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true