name: "CD - Development"

on:
  workflow_dispatch:
    inputs:
      trigger_event:
        description: "Ejecutar la acción manualmente"
        required: false
        default: "manual"
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  publish-images-job:
    if: github.event.pull_request.merged == true
    name: Publish Docker Images
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    with:
      workflow_file_path: "ghcr.io/snippetservices-group4/permissions-dev:latest"
    secrets: inherit

  deploy-vm-job:
    needs: publish-images-job
    name: Deploy Images in VM
    uses: SnippetServices-Group4/Workflows/.github/workflows/deploy-images-vm.yaml@main
    with:
      environment: "development"
      service_name: "permissions"
    secrets: inherit
